### ISSUE TITLE
Compatibility with sbt 1.2.8 and earlier

### ISSUE THREAD

**Issue by rtimush** [scalameta/sbt-scalafmt#92]
Hi,

The latest sbt-scalafmt release (2.3.3) doesn't work with sbt 1.2.8 and earlier anymore, because of https://github.com/sbt/sbt/issues/5049:
```
sbt:scalafmt-test> scalafmtAll
[error] java.lang.NoSuchMethodError: sbt.package$.singleFileJsonFormatter()Lsjsonnew/JsonFormat;
[error] 	at org.scalafmt.sbt.ScalafmtPlugin$ScalafmtAnalysis$.<init>(ScalafmtPlugin.scala:68)
[error] 	at org.scalafmt.sbt.ScalafmtPlugin$ScalafmtAnalysis$.<clinit>(ScalafmtPlugin.scala)
[error] 	at org.scalafmt.sbt.ScalafmtPlugin$.trackSourcesAndConfig(ScalafmtPlugin.scala:259)
...
```

The simplest fix would be to revert #89.

**Comment by poslegm** [comment]
Sorry for this confusion. I will cut 2.3.4 with fix ASAP
