### ISSUE TITLE
Network issue with new version 2.5.6 behind corporate firewall

### ISSUE THREAD

**Issue by christianknoepfle** [scalameta/sbt-scalafmt#411]
Hi,

we are using sbt and sbt-scalfmt for quite some time on our internal cicd-runner, which is located behind a corporate firewall. Internet access is limited but we can request to open https access to various sites.

Until last week sbt-scalafmt worked fine (we were using 2.5.5 and calling scalafmtCheckAll). Since our upgrade to 2.5.6 the sbt job get stuck and after 30min it errors out with

````
org.scalafmt.sbt.ScalafmtSbtReporter$ScalafmtSbtError: scalafmt: Missing config [/builds/enya-dap-core/source2landing/database-ingest/.scalafmt.conf]
````
The message is confusing because there is a `.scalafmt.conf`

The change was:
<img width="567" height="148" alt="Image" src="https://github.com/user-attachments/assets/c6292615-bcc8-4881-8271-7a0b3840f877" />

reverting back to 2.5.5 solves the issue.

Due to this long waiting period of 30min and the fact that it works on my local machine (sbt 1.9.7) where I have full internet access, I assume that some download is intended to happen from a location we have no access to. 

Any ideas on what has changed here? 

The log for 2.5.6 looks like this:
````
++ sbt --timings -Denv=dev -DbuildTimestamp=20251106111349 clean update scalafmtCheckAll test publish assembly doc

downloading sbt launcher 1.10.11
copying runtime jar...
[info] Updated file /builds/enya-dap-core/source2landing/database-ingest/project/build.properties: set sbt.version to 1.10.11
[info] welcome to sbt 1.10.11 (Amazon.com Inc. Java 17.0.17)
[info] loading settings for project database-ingest-build from plugins.sbt...
[info] loading project definition from /builds/enya-dap-core/source2landing/database-ingest/project
[info] compiling 1 Scala source to /builds/enya-dap-core/source2landing/database-ingest/project/target/scala-2.12/sbt-1.0/classes ...
[info] done compiling
[info] Total time: 15005 ms
...
[info] scalafmt: Checking 11 Scala sources (/builds/enya-dap-core/source2landing/database-ingest)...
[info] Total time: 1938827 ms
[info]   database-ingest / Compile / scalafmtCheck                                : 1938776 ms
[info]   database-ingest / Test / scalafmtCheck                                   :  600010 ms
[info]   database-ingest / Test / unmanagedSources / allInputPathsAndAttributes   :      48 ms
[info]   database-ingest / Compile / unmanagedSources / allInputPathsAndAttributes:      24 ms
[info]   database-ingest / Compile / unmanagedSources / inputFileStamps           :      11 ms
[info]   database-ingest / IntegrationTest / scalafmtCheck                        :       3 ms
[info]   database-ingest / Test / unmanagedSources / inputFileStamps              :       2 ms
[error] org.scalafmt.sbt.ScalafmtSbtReporter$ScalafmtSbtError: scalafmt: Missing config [/builds/enya-dap-core/source2landing/database-ingest/.scalafmt.conf]
[error] (Test / scalafmtCheck) org.scalafmt.sbt.ScalafmtSbtReporter$ScalafmtSbtError: scalafmt: Missing config [/builds/enya-dap-core/source2landing/database-ingest/.scalafmt.conf]
[error] Total time: 1939 s (0:32:19.0), completed Nov 6, 2025, 11:46:43 AM
Total time: 1964699 ms
````

With 2.5.5 scalafmt finishes in 6secs
````
...
[info] scalafmt: Checking 11 Scala sources (/builds/enya-dap-core/source2landing/database-ingest)...
[info] scalafmt: Checking 5 Scala sources (/builds/enya-dap-core/source2landing/database-ingest)...
[info] Total time: 5636 ms
[info]   database-ingest / Compile / scalafmtCheck                                : 5570 ms
[info]   database-ingest / Test / scalafmtCheck                                   : 5369 ms
[info]   database-ingest / Test / unmanagedSources / allInputPathsAndAttributes   :   31 ms
[info]   database-ingest / Compile / unmanagedSources / allInputPathsAndAttributes:   31 ms
[info]   database-ingest / Test / unmanagedSources / inputFileStamps              :    7 ms
[info]   database-ingest / Compile / unmanagedSources / inputFileStamps           :    3 ms
[info]   database-ingest / IntegrationTest / scalafmtCheck                        :    3 ms
[success] Total time: 6 s, completed Nov 6, 2025, 10:58:29 AM
````

Thanks a lot, Christian

**Comment by kitbellew** [comment]
more specifically: how do you tell your build where to get dependencies?

**Comment by mino5** [comment]
@christianknoepfle I’m not sure if it’s the same issue in your case, but I had it stuck for quite a while too, and upgrading Java from 22 to 25 resolved it for me. Of course, that upgrade might not be an option on your end, but I thought I’d share just in case it helps.

**Comment by kitbellew** [comment]
> ```
> org.scalafmt.sbt.ScalafmtSbtReporter$ScalafmtSbtError: scalafmt: Missing config [/builds/enya-dap-core/source2landing/database-ingest/.scalafmt.conf]
> ```
> 
> The message is confusing because there is a `.scalafmt.conf`

Let me repeat. What does that file contain?

As it stands, I don't know what has changed to behave like this. Anything else special to your environment? Credentials for these custom repositories? Are they fully up-to-date with external repos?

The only thing I can think of as a culprit is this change: scalameta/scalafmt#4962. However, to prove this, you'd need to use the scalafmt binary v3.9.10 or later (NOT the sbt plugin, https://scalameta.org/scalafmt/docs/installation.html#cli) and provide these custom repositories the way coursier expects you to (https://get-coursier.io/docs/other-repositories, but don't ask me how to use it, I don't know.)

**Comment by kitbellew** [comment]
> Hmm, I have observed a build problem due to binary incompatibility in Kinetic Merge that may be related to this ticket.
> 
> ```
> [error] java.lang.NoSuchMethodError: 'java.lang.String scala.cli.config.Key$StringListEntry$.$lessinit$greater$default$3()'
> ```

you should report this problem in the repository which maintains `scala-cli`, not here.

**Comment by sageserpent-open** [comment]
> I presume I'm seeing a classic dependency hell of incompatible transitive dependencies, in my case the one in the project meta-build and the one in the ScalaFmt plugin.

I don't think Scala CLI is the problem here, rather the *dependencies* that lead to it. I could well be wrong, though.

Anyway, I'm alright with reverting the upgrade; good luck with your problem solving!

**Comment by kitbellew** [comment]
please check with v2.6.0, it now uses sbt's own download mechanism so if that is configured correctly, the formatter should work.

**Comment by sageserpent-open** [comment]
Thank you, @kitbellew - I can confirm that `sbt packageExecutable` works with v2.6.0 in the Kinetic Merge repository.

**Comment by christianknoepfle** [comment]
Thank you very muc @kitbellew, same here. It now works as expected
