### ISSUE TITLE
Scala 3.3  ScalafmtSbtError for type with match

### ISSUE THREAD

**Issue by patriknw** [scalameta/sbt-scalafmt#285]
sbt-scalfmt version 2.5.2 and 2.4.2

We have this code in Akka for Scala 3.3
https://github.com/akka/akka/blob/dd381c1803d0a3cb171ae8fecebfacffce1dd424/akka-actor-typed/src/main/scala-3/akka/actor/typed/internal/receptionist/Platform.scala#L13-L23

Error from scalafmt:
```
[error] (Compile / scalafmt) org.scalafmt.sbt.ScalafmtSbtReporter$ScalafmtSbtError: scalafmt: /Users/patrik/dev/akka/akka-actor-typed/src/main/scala-3/akka/actor/typed/internal/receptionist/Platform.scala:16: error: ; expected but match found
[error]   type Service[K <: Aux[_]] = K match {
```

It compiles with Scala 3.3.1 when disabling scalafmt.

Corresponding Scala 2.13 source https://github.com/akka/akka/blob/main/akka-actor-typed/src/main/scala-2.13/akka/actor/typed/internal/receptionist/Platform.scala

We are open to changing the Scala 3 source code if you think it should be written in another way.

How to reproduce:

1. clone https://github.com/akka/akka
2. sbt
3. ++3.3
4. akka-actor-typed/scalafmt

**Comment by patriknw** [comment]
sorry, reported in wrong place, and it is fixed in later version of scalafmt itself
